spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/unio
    username: unio
    password: unio
  jpa:
    hibernate:
      ddl-auto: create-drop
  flyway:
    enabled: false

server:
  port: 0
